=== wlowP/JavaCodes/IOPractice/files/xml/dtd/students.dtd
<!-- 📌📌约束标签名称及子级标签 -->
<!-- 格式: <!ELEMENT 标签名 标签内容或子标签列表> -->
<!-- ●标签内容:
        (#PCDATA): 表示标签内容是字符串
        EMPTY: 标签标签内容为空, 不能有值
        ANY: 任意, 有没有值都行
     ●子标签列表:
        子标签名用逗号隔开来包在小括号里.
        可以加上+*?的修饰符, 限制子标签出现的次数. 不加则默认表示只出现一次
            +:大于等于一次; *:任意次; ?:零次或一次
        多个子标签名用"|"隔开可以起到'或'的效果, 只能出现其中一个
 -->
<!ELEMENT students (student+)>
<!ELEMENT student (id, name, age, book+, score+)>
    <!ATTLIST student
            attr CDATA #IMPLIED
            >
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT book (title, author, description, date|price, booktag)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT description ANY>
        <!ELEMENT date (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT booktag EMPTY>
    <!-- 📌📌约束标签属性. -->
    <!-- 格式: <!ATTLIST 标签名称 (属性名称 属性类型 约束条件 默认值(可不写))*> -->
    <!-- ●属性类型:
            CDATA: 字符串类型
            ID: 同级标签中不能重复
            (...|...|...): 枚举类型, 只能从列出的值中选一个
                📌枚举中的字符串不能加引号, 否则起不到限制效果
         ●约束条件:
            #REQUIRED: 属性必须要存在
            #IMPLIED: 属性可有可无
            #FIXED: 属性是固定值, 后面可以加上默认值
     -->
    <!ELEMENT score (#PCDATA)>
        <!ATTLIST score
            id ID #REQUIRED
            subject CDATA #REQUIRED
            mark CDATA #REQUIRED
            pass (合格|不合格|评测中) #REQUIRED
            type CDATA #FIXED "科目成绩"
            >

=== wlowP/JavaCodes/files/xml/students.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!-- 外联引入DTD文档约束 -->
<!DOCTYPE students SYSTEM './dtd/students.dtd'>
<students>
    <student>
        <id>001</id>
        <name>张三</name>
        <age>18</age>
        <book>
            <title>钢铁是怎样炼成的</title>
            <author>尼古拉·奥斯特洛夫斯基</author>
            <!-- <date>1933</date> -->
            <price>68</price>
            <booktag/>
        </book>
        <book>
            <title>朝花夕拾</title>
            <author>鲁迅</author>
            <date>1928</date>
            <!-- <price>35</price> -->
            <booktag/>
        </book>
        <score id="001" subject="数学" mark="99" pass="合格"/>
        <score id="002" subject="JAVA程序设计" mark="98" pass="合格"/>
    </student>
    <student attr="some_attr">
        <id>002</id>
        <name>李四</name>
        <age>19</age>
        <book>
            <title>围城</title>
            <author>钱钟书</author>
            <date>1946</date>
            <price>40</price>
            <booktag/>
        </book>
        <score id="003" mark="95" pass="合格" subject="学术英语"/>
    </student>
</students>
